### PR TITLE
Support environment variables API

### PR DESCRIPTION
**Pull request by udzura**
Hi, I want to use this API!

### CODE REVIEW

**Comment by udzura** [comment]
And please create a new release after merging this!

(or, give me gem admin to `udzura@udzura.jp`

**Comment by litencatt** [comment]
@udzura 
Thanks for a PR!
And we want tests for this new feature API with VCR hopefully.

**Comment by udzura** [comment]
I have forgotten how to use VCR!!!!!!!! Please wait a moment

**Comment by udzura** [comment]
@litencatt Please check it out 🙏

**Pull request merged**
